name: neucalcu
description: A new Flutter application.

publish_to: 'none'

version: 1.2.2+8

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_circle_color_picker: ^0.3.0
  google_fonts: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  math_expressions: ^2.4.0
  provider: ^6.0.5
  url_launcher: ^6.1.12

  # cupertino_icons: ^0.1.3
  # flutter_circle_color_picker: ^0.3.0
  # google_fonts: ^1.1.2
  # hive: ^0.5.1+1
  # hive_flutter: ^0.3.1
  # line_awesome_icons: ^1.0.4+2
  # math_expressions: ^0.4.0
  # provider: ^2.0.1+1
  # url_launcher: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  


# dependency_overrides:
#   dartx: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

